### ISSUE TITLE
Roadmap to MVP

### ISSUE THREAD

**Issue by peterhurford** [charityscience/csh-sms#11]
* Create DB
---- Postgres with three tables (contacts, groups, messages)
---- Contacts can have many groups, groups can have many contacts, contacts can have many messages, messages have one contact

* Continually running service to process incoming texts (e.g., `REMIND Nathan 25/04/13`), put people in the database
---- Use API of provider
---- Implement business rules

* Job that runs three times a day will read from the database and send all the messages that need sending using TextLocal API
---- Use API of provider
---- Implement business rules

* Host on AWS (remember to use Indian region)

**Comment by peterhurford** [comment]
TODO FOR INITIAL LAUNCH:

* [x] Initial job for processing texts - **Done** - #17 
* [x] Initial job for sending reminders - **Done** - #25 
* [x] CSV batch upload - **Done** - #22 
* [x] Library for sending and receiving texts - **Done** - #49
* [x] DB Schema - **Done**
* [x] Django and text integration for process text job - **Done** - #27 
* [x] Django and text integration for sending reminders job - **Done** - #27
* [x] Host process text job on AWS - **Done** - #37
* [x] Host reminder sending job on AWS - **Done** - #37 
* [x] Automated E2E testing for process / remind - **Done** - #49 
* [x] Automatic E2E testing written and working - **Done** - #49 
* [x] Revise failure messages to give new reply number - **Done** - #51
* [x] Pregnancy texts + unit tests + E2E live test - **Done** - #49 and #52
* [x] Make sure we subscribe every reminder and subscriber - **Done** - #55
* [x] Implement time of day (send reminders at 4pm IST, send registration responses immediately)  - **Done** - #56
* [x] Redeploy in India region and on CSH AWS account - **Done**
* [x] E2E testing for CSV upload - **Done** - #58 
* [x] Sign up some phones (in both English and Hindi), fake their birthdays, and look at the logfiles - **Done**
* [x] Add a timestamp to the `Message` object - **Done** - #61

STAGING:

* [x] Change how we read messages to avoid conflicts (Read two days worth of messages, do not filter on `isNew`, instead check DB of `Contact` and `Message` objects) + unit tests, merge to staging - **Done** - #69 
* [x] Create a `Message` object when processing a text + unit / live tests, merge to staging - **Done** - #63 and #65
* [x] Create a `Message` object when sending texts + unit / live tests, merge to staging - **Done** - #62
* [x] When we can't process texts, create a `Message` and `Contact` object anyway; handle updating the `Contact` object when people text in again + unit / live tests, merge to staging - **Done** #62 and #63
* [x] Existing contacts with Hindi language preference don't change to English if we're sent English pregnancy update keyword, merge to staging - **Done** - #69
* [x] Add all desired timestamps to objects + unit / live tests, merge to staging - **Done** - #70
* [x] Migrate from HSPSMS to TextLocal, merge to staging - **Done** - #71
* [x] Confirm fix for live test inbox collision, confirm live tests pass, merge staging to master - **Done** - #72
* [x] Gujarati live tests run - **Done** #73
* [ ] Change time text reminders go out to 3:30pm IST - Not Started
* [ ] Add and test Bengali translations of messages - Not Started

LAUNCH:

* [ ] **PARTIAL LAUNCH:** Migrate 1% of Telerivet and look at the logfiles - Not Started
* [ ] **PARTIAL LAUNCH:** Change text-in number - Not Started
* [ ] Database backups - Not Started
* [ ] Logfile backups - Not Started
* [ ] **FULL LAUNCH:** Migrate everyone off of Telerivit - Not Started

TODO AFTER LAUNCH:

* [ ] Properly IP whitelist the server - Not Started
* [ ] Verify translations (make sure they are latest versions first) - Not Started
* [ ] Scale testing + make sure app doesn't deadlock - Not Started
* [ ] Handle log file bloat - Not Started
* [ ] E2E tests for hospital-style formatted csv - Not Started
* [ ] What happens if we miss a text? - Not Started
* [ ] Allow changing of birthdate via a second text sign up message  - Not Started
* [ ] Run e2e tests daily and email a report - Not Started
* [ ] Email weekly summaries of the app - Not Started
* [ ] Printable call lists based people based on time of vaccine (i.e. due in next of week or not) and origin of sign up (hospital, org, etc.)
* [ ] Allow people who sign up with a birth date in the future to become a pregnancy sign up, but don't let them sign up more than 10 months in the future - Not Started
* [ ] If people sign up with a birth date in the future, text them back looking for a confirmation - Not Started
